/**
 * CodeGenCapability (Wave 5 T01).
 *
 * 给 ctrl 生成 typed accessor TS 源码, 让业务能用 enum + 类型化 API 切 state, 避免 magic number.
 *
 *   CodeGenCapability.generate(ctrl) → string  (TS 源码)
 *   CodeGenCapability.getFilename(ctrl) → "${PascalCaseCtrlName}.gen.ts"
 *
 * 生成结构 (示例 ctrl "HoverBtn", states ["Normal", "Hover", "Pressed"]):
 *
 *   // Generated by state-controller. Don't edit.
 *   import { StateController } from "<...>";
 *   import { EventCapability } from "<...>";
 *   import { SelectedPageIdCapability } from "<...>";
 *
 *   export enum HoverBtnStates { Normal = 0, Hover = 1, Pressed = 2 }
 *
 *   const STATE_IDS = [100, 101, 102];  // stateId 数组, 用于跨 reorder 稳定
 *
 *   export class HoverBtnAccessor {
 *       private ctrl: any;
 *       static from(node: any) { ... }
 *       get current(): HoverBtnStates { ... }
 *       goTo(s: HoverBtnStates): boolean { return SelectedPageIdCapability.setStateById(this.ctrl, STATE_IDS[s]); }
 *       onChange(cb: (from, to) => void): () => void { ... EventCapability.on ... }
 *   }
 *
 * Panel UI 端调用 generate() 拿源码, 由用户/Panel 写入到磁盘 (本 capability 不直接写文件).
 */

import { CapabilityRegistry } from "../CapabilityRegistry";
import { ICapability } from "../Capability";

/** 把任意字符串转 PascalCase 合法标识符. */
function toPascalCase(input: string): string {
    if (!input) return "";
    // 把非 ASCII / 非 [A-Za-z0-9_] 换成 _
    const cleaned = input.replace(/[^A-Za-z0-9_]+/g, "_");
    const parts = cleaned.split("_").filter(p => p.length > 0);
    if (parts.length === 0) return "";
    return parts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join("");
}

/** sanitize 成合法 TS 标识符 (enum 成员名). 数字开头加 _ 前缀. */
function toSafeIdent(input: string, fallback: string): string {
    if (!input) return fallback;
    let s = input.replace(/[^A-Za-z0-9_]+/g, "_");
    if (s.length === 0) return fallback;
    if (/^[0-9]/.test(s)) s = "_" + s;
    return s;
}

/** ASCII fallback: 非 ASCII 字符全部转 _ 后, 若结果空 → 用 hash hex 作 fallback. */
function safeFileBase(input: string): string {
    const pascal = toPascalCase(input);
    if (pascal.length > 0) return pascal;
    // 非 ASCII 全失败 → 用一个稳定的非空 fallback
    let hash = 0;
    for (let i = 0; i < input.length; i++) {
        hash = ((hash << 5) - hash + input.charCodeAt(i)) | 0;
    }
    return "Ctrl_" + Math.abs(hash).toString(16);
}

export const CodeGenCapability: ICapability & {
    generate: (ctrl: any) => string,
    getFilename: (ctrl: any) => string,
} = {
    name: "codeGen",

    getFilename(ctrl: any): string {
        if (!ctrl || !ctrl.ctrlName) return "Untitled.gen.ts";
        return safeFileBase(ctrl.ctrlName) + ".gen.ts";
    },

    generate(ctrl: any): string {
        if (!ctrl || !ctrl._states || ctrl._states.length === 0) return "";

        const ctrlName = ctrl.ctrlName || "Untitled";
        const className = safeFileBase(ctrlName);
        const enumName = className + "States";
        const accessorName = className + "Accessor";

        const states = ctrl._states;
        const enumLines: string[] = [];
        const stateIds: number[] = [];

        // 用 Map 防同名 enum member
        const seen: { [k: string]: boolean } = {};
        for (let i = 0; i < states.length; i++) {
            const s = states[i];
            let ident = toSafeIdent(s.name || ("S" + i), "S" + i);
            // 防重: 如果已有同名加 _i
            if (seen[ident]) ident = ident + "_" + i;
            seen[ident] = true;
            enumLines.push(`    ${ident} = ${i},`);
            stateIds.push(typeof s.stateId === "number" ? s.stateId : -1);
        }

        const out: string[] = [];
        out.push("// Generated by state-controller CodeGenCapability. Don't edit by hand.");
        out.push("// To regenerate: Panel → CodeGen → Save.");
        out.push("");
        out.push(`import { StateController } from "../controller/StateController";`);
        out.push(`import { EventCapability } from "../controller/capabilities/EventCapability";`);
        out.push(`import { SelectedPageIdCapability } from "../controller/capabilities/SelectedPageIdCapability";`);
        out.push("");
        out.push(`export enum ${enumName} {`);
        out.push(enumLines.join("\n"));
        out.push(`}`);
        out.push("");
        out.push(`/** stateId by index — 跨 reorder 仍能定位原 state. */`);
        out.push(`const STATE_IDS: number[] = [${stateIds.join(", ")}];`);
        out.push("");
        out.push(`export class ${accessorName} {`);
        out.push(`    private constructor(private ctrl: any) {}`);
        out.push("");
        out.push(`    /** 从节点拿到 accessor. 节点上必须挂有同名 StateController. */`);
        out.push(`    public static from(node: any): ${accessorName} | null {`);
        out.push(`        if (!node) return null;`);
        out.push(`        const ctrl = node.getComponent && node.getComponent(StateController);`);
        out.push(`        if (!ctrl) return null;`);
        out.push(`        return new ${accessorName}(ctrl);`);
        out.push(`    }`);
        out.push("");
        out.push(`    /** 当前 state (enum 值). */`);
        out.push(`    public get current(): ${enumName} {`);
        out.push(`        return this.ctrl.selectedIndex as ${enumName};`);
        out.push(`    }`);
        out.push("");
        out.push(`    /** 切到指定 state, 走 stateId 稳定路径. 返回 true=成功. */`);
        out.push(`    public goTo(s: ${enumName}): boolean {`);
        out.push(`        const id = STATE_IDS[s];`);
        out.push(`        if (typeof id !== "number" || id < 0) return false;`);
        out.push(`        return SelectedPageIdCapability.setStateById(this.ctrl, id);`);
        out.push(`    }`);
        out.push("");
        out.push(`    /** 订阅 state 切换. cb(from, to) 形式. 返回 unsubscribe(). */`);
        out.push(`    public onChange(cb: (from: ${enumName}, to: ${enumName}) => void): () => void {`);
        out.push(`        const handler = (p: any) => cb(p.fromState as ${enumName}, p.toState as ${enumName});`);
        out.push(`        EventCapability.on(this.ctrl, "stateChanged", handler);`);
        out.push(`        return () => EventCapability.off(this.ctrl, "stateChanged", handler);`);
        out.push(`    }`);
        out.push(`}`);
        out.push("");

        return out.join("\n");
    },
};

CapabilityRegistry.register(CodeGenCapability);
