/**
 * CodeGenCapability 契约 (Wave 5 T01)
 *
 * 给 ctrl 生成静态 typed accessor TS 文件, 让业务代码能用 enum + 类型化 API 切 state.
 *
 *   CodeGenCapability.generate(ctrl) → string  (TS 源码)
 *   CodeGenCapability.getFilename(ctrl) → "${PascalCaseName}.gen.ts"
 *
 * 生成内容必含:
 *   - enum {CtrlName}States { S1 = 0, S2 = 1, ... }
 *   - class {CtrlName}Accessor { static from(node) / goTo / current / onChange }
 *   - 文件头 "// Generated by state-controller. Don't edit."
 *
 * Red: 模块不存在.
 */

declare global {
    const CC_EDITOR: boolean;
    const cc: any;
    const Editor: any;
}

beforeAll(() => {
    (globalThis as any).CC_EDITOR = true;
    (globalThis as any).Editor = {
        log: () => {}, warn: () => {}, error: () => {},
        Utils: { refreshSelectedInspector: () => {} },
    };
});

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { StateController } = require("../../assets/script/controller/StateController");

function setupCtrl(name?: string, stateNames?: string[]) {
    const ccLocal = (globalThis as any).cc;
    const ctrlNode = new ccLocal.Node(name || "CtrlNode");
    const ctrl = ctrlNode.addComponent(StateController);
    (ctrl as any).__preload();
    if (name) ctrl.ctrlName = name;
    if (stateNames && stateNames.length > 0) {
        // 用 setter 替换 states
        const StateValue = require("../../assets/script/controller/StateController").StateValue;
        const newStates = stateNames.map((n, i) => StateValue.create(n, i + 100));
        ctrl.states = newStates;
    }
    return { ctrl };
}

describe("CodeGenCapability (Wave 5 T01)", () => {
    it("模块存在 + name = codeGen + 注册", () => {
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const Mod = require("../../assets/script/controller/capabilities/CodeGenCapability");
        expect(Mod.CodeGenCapability).toBeDefined();
        expect(Mod.CodeGenCapability.name).toBe("codeGen");
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const { CapabilityRegistry } = require("../../assets/script/controller/CapabilityRegistry");
        expect(CapabilityRegistry.get("codeGen")).toBeDefined();
    });

    it("generate(ctrl) 返回非空 TS 源码, 含 Don't edit header", () => {
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const { CodeGenCapability } = require("../../assets/script/controller/capabilities/CodeGenCapability");
        const { ctrl } = setupCtrl("HoverBtn", ["Normal", "Hover", "Pressed"]);
        const src = CodeGenCapability.generate(ctrl);
        expect(typeof src).toBe("string");
        expect(src.length).toBeGreaterThan(50);
        expect(src).toMatch(/Don't edit|do not edit/i);
    });

    it("生成的 enum 含所有 state 名 + 数值 = index", () => {
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const { CodeGenCapability } = require("../../assets/script/controller/capabilities/CodeGenCapability");
        const { ctrl } = setupCtrl("HoverBtn", ["Normal", "Hover", "Pressed"]);
        const src = CodeGenCapability.generate(ctrl);
        expect(src).toMatch(/export\s+enum\s+HoverBtnStates/);
        expect(src).toMatch(/Normal\s*=\s*0/);
        expect(src).toMatch(/Hover\s*=\s*1/);
        expect(src).toMatch(/Pressed\s*=\s*2/);
    });

    it("生成的 Accessor 类含 from/goTo/current/onChange", () => {
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const { CodeGenCapability } = require("../../assets/script/controller/capabilities/CodeGenCapability");
        const { ctrl } = setupCtrl("HoverBtn", ["Normal", "Hover"]);
        const src = CodeGenCapability.generate(ctrl);
        expect(src).toMatch(/class\s+HoverBtnAccessor/);
        expect(src).toMatch(/static\s+from\s*\(/);
        expect(src).toMatch(/goTo\s*\(/);
        expect(src).toMatch(/current/);
        expect(src).toMatch(/onChange\s*\(/);
    });

    it("getFilename → 'PascalCase.gen.ts'", () => {
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const { CodeGenCapability } = require("../../assets/script/controller/capabilities/CodeGenCapability");
        const { ctrl } = setupCtrl("hover_btn_ctrl");
        expect(CodeGenCapability.getFilename(ctrl)).toBe("HoverBtnCtrl.gen.ts");

        const b = setupCtrl("已购买面板");
        // 非 ASCII fallback
        const fn = CodeGenCapability.getFilename(b.ctrl);
        expect(fn.endsWith(".gen.ts")).toBe(true);
        expect(fn.length).toBeGreaterThan(".gen.ts".length);
    });

    it("非法 state 名 (含空格/连字符) sanitized 成合法 enum 标识符", () => {
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const { CodeGenCapability } = require("../../assets/script/controller/capabilities/CodeGenCapability");
        const { ctrl } = setupCtrl("Btn", ["normal state", "hover-active", "1press"]);
        const src = CodeGenCapability.generate(ctrl);
        // 必须全部出现 (具体形态自由, 但都得能成为合法标识符)
        expect(src).toMatch(/normal_state|NormalState/);
        expect(src).toMatch(/hover_active|HoverActive/);
        // 数字开头的 prefix 加下划线
        expect(src).toMatch(/_1press|S_1press|S1press/);
    });

    it("空/null ctrl → generate 返回空字符串, getFilename 返回 'Untitled.gen.ts'", () => {
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const { CodeGenCapability } = require("../../assets/script/controller/capabilities/CodeGenCapability");
        expect(CodeGenCapability.generate(null)).toBe("");
        expect(CodeGenCapability.getFilename(null)).toBe("Untitled.gen.ts");
    });

    it("生成的 goTo 用 stateId 而非 index (跨 reorder 稳定)", () => {
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const { CodeGenCapability } = require("../../assets/script/controller/capabilities/CodeGenCapability");
        const { ctrl } = setupCtrl("Btn", ["Normal", "Hover"]);
        const src = CodeGenCapability.generate(ctrl);
        // goTo 实现里要引用 SelectedPageIdCapability.setStateById
        expect(src).toMatch(/setStateById|SelectedPageIdCapability/);
    });
});
